import { Body, Controller, ForbiddenException, Injectable, Module, Param, Post } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { InjectRepository, TypeOrmModule } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { IsInt, IsObject, IsOptional, IsString } from 'class-validator';
import { AIProposalStatus, ApiException, AuthenticatedUser, CurrentUser, ErrorCode } from './common';
import { AIActionProposal } from './entities';
@Injectable()export class AiService{constructor(@InjectRepository(AIActionProposal)private r:Repository<AIActionProposal>,private c:ConfigService){}chat(message:string){if(!this.c.get<boolean>('CHAT_ASSISTANT_ENABLED'))throw new ApiException(ErrorCode.AI_PROVIDER_UNAVAILABLE,'Chat Assistant is unavailable; manual workflow remains available.',503);return{message:`Demo response: ${message}`,readOnly:true,demoData:true};}async propose(d:{caseId?:string;actionType:string;previewPayload:Record<string,unknown>},u:AuthenticatedUser){if(!this.c.get<boolean>('AGENTIC_ASSISTANT_ENABLED'))throw new ApiException(ErrorCode.AI_PROVIDER_UNAVAILABLE,'Agentic Assistant is unavailable; manual workflow remains available.',503);if(['APPROVE_PLAN','CLOSE_CASE','ARCHIVE_CASE','DELETE_EVIDENCE','CHANGE_ROLE','EDIT_APPROVED_PLAN'].includes(d.actionType))throw new ForbiddenException('AI cannot perform this action.');return this.r.save(this.r.create({...d,createdByProfileId:u.officerProfileId,status:AIProposalStatus.PENDING,expiresAt:new Date(Date.now()+15*60_000)}));}async confirm(id:string,version:number,u:AuthenticatedUser){const p=await this.r.findOneByOrFail({id,createdByProfileId:u.officerProfileId});if(p.status!==AIProposalStatus.PENDING||p.version!==version||p.expiresAt<new Date())throw new ForbiddenException('Proposal cannot be confirmed.');p.status=AIProposalStatus.CONFIRMED;await this.r.save(p);return{proposal:p,committed:false,note:'Register a permission-checked domain handler for this exact action type before enabling writes.'};}}
class ChatDto{@IsString()message:string}class ProposalDto{@IsOptional()@IsString()caseId?:string;@IsString()actionType:string;@IsObject()previewPayload:Record<string,unknown>}class ConfirmDto{@IsInt()expectedVersion:number}
@Controller('ai')export class AiController{constructor(private s:AiService){}@Post('chat/messages')chat(@Body()d:ChatDto){return this.s.chat(d.message)}@Post('agent/messages')propose(@Body()d:ProposalDto,@CurrentUser()u:AuthenticatedUser){return this.s.propose(d,u)}@Post('agent/proposals/:id/confirm')confirm(@Param('id')id:string,@Body()d:ConfirmDto,@CurrentUser()u:AuthenticatedUser){return this.s.confirm(id,d.expectedVersion,u)}}
@Module({imports:[TypeOrmModule.forFeature([AIActionProposal])],providers:[AiService],controllers:[AiController]})export class AiModule{}
