import { Body, Controller, ForbiddenException, Get, Injectable, Module, NotFoundException, Param, Patch, Post } from '@nestjs/common';
import { InjectRepository, TypeOrmModule } from '@nestjs/typeorm';
import { In, Repository } from 'typeorm';
import { area, bbox, centroid, feature, kinks, length, polygonToLine } from '@turf/turf';
import { createHash } from 'crypto';
import { ConfigService } from '@nestjs/config';
import { IsArray, IsBoolean, IsDateString, IsEnum, IsInt, IsNumber, IsObject, IsOptional, IsString, IsUUID, Max, Min } from 'class-validator';
import { AssessmentStatus, AuthenticatedUser, CurrentUser, DeviationCategory, EvidenceStatus, MissionStatus, MissionType, OfficerRole, PlanStatus, PlanType, Roles, SignalDecisionType, SignalStatus, TechnicalModuleType } from './common';
import { AuditEvent, CaseAssignment, EvidenceGap, EvidenceItem, FieldMission, FieldObservation, LandPatch, Milestone, MonitoringEvent, Notification, OfficerProfile, PlanVersion, PrioritySignal, Region, RestorationCase, SignalDecision, TechnicalAssessment, TechnicalModule, User } from './entities';
import { ScopePolicy } from './database';
import { WorkflowService } from './workflow';

@Injectable()export class AuditService{constructor(@InjectRepository(AuditEvent)private r:Repository<AuditEvent>){}append(action:string,targetType:string,targetId:string|undefined,caseId:string|undefined,u:AuthenticatedUser,metadata:Record<string,unknown>={},justification?:string){return this.r.save(this.r.create({actorProfileId:u.officerProfileId,actorRole:u.role,action,targetType,targetId,caseId,metadata,justification}));}list(caseId?:string){return this.r.find({where:caseId?{caseId}:{},order:{createdAt:'DESC'},take:200});}}
@Injectable()export class NotificationService{constructor(@InjectRepository(Notification)private r:Repository<Notification>){}create(recipientProfileId:string,type:string,title:string,message:string,deepLink?:string){return this.r.save(this.r.create({recipientProfileId,type,title,message,deepLink}));}list(id:string){return this.r.find({where:{recipientProfileId:id},order:{createdAt:'DESC'}});}async read(id:string,profileId:string){const n=await this.r.findOne({where:{id,recipientProfileId:profileId}});if(!n)throw new NotFoundException();n.readAt=new Date();return this.r.save(n);}}

@Injectable()export class UserService{constructor(@InjectRepository(User)private users:Repository<User>,@InjectRepository(OfficerProfile)private profiles:Repository<OfficerProfile>){}async list(){const p=await this.profiles.find();return(await this.users.find()).map(u=>({id:u.id,email:u.email,isActive:u.isActive,profile:p.find(x=>x.userId===u.id)}));}}
@Controller('users')@Roles(OfficerRole.SYSTEM_ADMINISTRATOR)export class UserController{constructor(private s:UserService){}@Get()list(){return this.s.list();}}

@Injectable()export class RegionService{constructor(@InjectRepository(Region)private r:Repository<Region>){}list(){return this.r.find({order:{type:'ASC',name:'ASC'}})}children(id:string){return this.r.find({where:{parentId:id},order:{name:'ASC'}})}}
@Controller('regions')export class RegionController{constructor(private s:RegionService){}@Get()list(){return this.s.list()}@Get(':id/children')children(@Param('id')id:string){return this.s.children(id)}}

@Injectable()export class SignalService{constructor(@InjectRepository(PrioritySignal)private r:Repository<PrioritySignal>,@InjectRepository(SignalDecision)private d:Repository<SignalDecision>,private audit:AuditService,private notes:NotificationService){}list(){return this.r.find({order:{createdAt:'DESC'}})}async decide(id:string,input:{decision:SignalDecisionType;justification:string;districtId?:string;districtOfficerId?:string},u:AuthenticatedUser){const s=await this.r.findOneByOrFail({id});if(!input.justification.trim())throw new ForbiddenException('Justification is required.');if(input.decision===SignalDecisionType.ACCEPT&&(!input.districtId||!input.districtOfficerId))throw new ForbiddenException('District and District Officer are required.');s.status=input.decision===SignalDecisionType.ACCEPT?SignalStatus.ACCEPTED:input.decision===SignalDecisionType.DISMISS?SignalStatus.DISMISSED:SignalStatus.SCREENING_REQUESTED;s.districtId=input.districtId??s.districtId;s.assignedDistrictOfficerId=input.districtOfficerId??s.assignedDistrictOfficerId;await this.r.save(s);const d=await this.d.save(this.d.create({signalId:id,actorProfileId:u.officerProfileId,decision:input.decision,justification:input.justification,districtId:input.districtId,districtOfficerId:input.districtOfficerId}));await this.audit.append(`SIGNAL_${input.decision}`,'PrioritySignal',id,undefined,u,{},input.justification);if(input.districtOfficerId)await this.notes.create(input.districtOfficerId,'SIGNAL_ASSIGNMENT','Priority signal assigned','A new priority signal was assigned.','/district/signals');return{signal:s,decision:d};}}
class SignalDecisionDto{@IsEnum(SignalDecisionType)decision:SignalDecisionType;@IsString()justification:string;@IsOptional()@IsUUID()districtId?:string;@IsOptional()@IsUUID()districtOfficerId?:string}
@Controller('signals')export class SignalController{constructor(private s:SignalService){}@Get()list(){return this.s.list()}@Post(':id/decision')@Roles(OfficerRole.STATE_PROGRAMME_OFFICER)decide(@Param('id')id:string,@Body()d:SignalDecisionDto,@CurrentUser()u:AuthenticatedUser){return this.s.decide(id,d,u)}}

@Injectable()export class LandService{constructor(@InjectRepository(LandPatch)private r:Repository<LandPatch>,private cfg:ConfigService,private audit:AuditService){}calculate(geometry:any){if(!geometry||!['Polygon','MultiPolygon'].includes(geometry.type))throw new ForbiddenException('Only Polygon or MultiPolygon is supported.');const f=feature(geometry);const hectares=area(f)/10000;if(hectares<=0||hectares>Number(this.cfg.get('MAX_LAND_PATCH_HECTARES',25000)))throw new ForbiddenException('Polygon area is invalid.');if(kinks(f as any).features.length)throw new ForbiddenException('Polygon self-intersects.');let perimeter=0;try{perimeter=length(polygonToLine(f as any) as any,{units:'kilometers'})*1000}catch{}return{areaHectares:Number(hectares.toFixed(4)),perimeterMetres:Number(perimeter.toFixed(2)),centroid:centroid(f).geometry as unknown as Record<string,unknown>,boundingBox:bbox(f),polygonHash:createHash('sha256').update(JSON.stringify(geometry)).digest('hex'),valid:true,warnings:[] as string[]};}async create(d:{districtId:string;mandalId:string;villageId:string;geometry:Record<string,unknown>},u:AuthenticatedUser){const calc=this.calculate(d.geometry);const duplicate=await this.r.findOne({where:{districtId:d.districtId,polygonHash:calc.polygonHash}});if(duplicate)calc.warnings.push(`Possible duplicate: ${duplicate.id}`);const entity = Object.assign(new LandPatch(), {...d,...calc,createdByProfileId:u.officerProfileId});const p: LandPatch=await this.r.save(entity);await this.audit.append('LAND_PATCH_CREATED','LandPatch',p.id,undefined,u,{areaHectares:p.areaHectares});return p;}get(id:string){return this.r.findOneByOrFail({id})}}
class LandDto{@IsUUID()districtId:string;@IsUUID()mandalId:string;@IsUUID()villageId:string;@IsObject()geometry:Record<string,unknown>}
@Controller('land-patches')export class LandController{constructor(private s:LandService){}@Post()@Roles(OfficerRole.DISTRICT_RESTORATION_OFFICER)create(@Body()d:LandDto,@CurrentUser()u:AuthenticatedUser){return this.s.create(d,u)}@Get(':id')get(@Param('id')id:string){return this.s.get(id)}@Post(':id/validate')async validate(@Param('id')id:string){return this.s.calculate((await this.s.get(id)).geometry)}}

@Injectable()export class CaseService{constructor(@InjectRepository(RestorationCase)private r:Repository<RestorationCase>,@InjectRepository(CaseAssignment)private a:Repository<CaseAssignment>,@InjectRepository(PrioritySignal)private signals:Repository<PrioritySignal>,@InjectRepository(LandPatch)private patches:Repository<LandPatch>,private scope:ScopePolicy,private audit:AuditService){}async create(d:{signalId:string;landPatchId:string;title:string;objective:string},u:AuthenticatedUser){const s=await this.signals.findOneByOrFail({id:d.signalId});if(s.status!==SignalStatus.ACCEPTED||s.assignedDistrictOfficerId!==u.officerProfileId)throw new ForbiddenException('Signal is not assigned to you.');if(!(await this.patches.findOneByOrFail({id:d.landPatchId})).valid)throw new ForbiddenException('Land patch is invalid.');const c=await this.r.save(this.r.create({...d,districtOfficerId:u.officerProfileId,status:'LAND_PATCH_DRAFT' as any}));await this.a.save(this.a.create({caseId:c.id,officerProfileId:u.officerProfileId,role:u.role,assignmentType:'CASE_OWNER',active:true}));await this.audit.append('CASE_CREATED','RestorationCase',c.id,c.id,u);return c;}async list(u:AuthenticatedUser){if([OfficerRole.SYSTEM_ADMINISTRATOR,OfficerRole.STATE_PROGRAMME_OFFICER].includes(u.role))return this.r.find();if(u.role===OfficerRole.DISTRICT_RESTORATION_OFFICER)return this.r.find({where:{districtOfficerId:u.officerProfileId}});const ids=(await this.a.find({where:{officerProfileId:u.officerProfileId,active:true}})).map(x=>x.caseId);return ids.length?this.r.find({where:{id:In(ids)}}):[];}async get(id:string,u:AuthenticatedUser){await this.scope.assertCase(u,id);return this.r.findOneByOrFail({id})}async assign(id:string,d:{officerProfileId:string;role:OfficerRole;assignmentType:string},u:AuthenticatedUser){await this.scope.assertCase(u,id);const x=await this.a.save(this.a.create({caseId:id,...d,active:true}));await this.audit.append('CASE_ASSIGNMENT_CREATED','CaseAssignment',x.id,id,u);return x;}}
class CreateCaseDto{@IsUUID()signalId:string;@IsUUID()landPatchId:string;@IsString()title:string;@IsString()objective:string}class AssignmentDto{@IsUUID()officerProfileId:string;@IsEnum(OfficerRole)role:OfficerRole;@IsString()assignmentType:string}
@Controller('cases')export class CaseController{constructor(private s:CaseService){}@Post()@Roles(OfficerRole.DISTRICT_RESTORATION_OFFICER)create(@Body()d:CreateCaseDto,@CurrentUser()u:AuthenticatedUser){return this.s.create(d,u)}@Get()list(@CurrentUser()u:AuthenticatedUser){return this.s.list(u)}@Get(':id')get(@Param('id')id:string,@CurrentUser()u:AuthenticatedUser){return this.s.get(id,u)}@Post(':id/assignments')@Roles(OfficerRole.DISTRICT_RESTORATION_OFFICER)assign(@Param('id')id:string,@Body()d:AssignmentDto,@CurrentUser()u:AuthenticatedUser){return this.s.assign(id,d,u)}}

@Injectable()export class MissionService{constructor(@InjectRepository(FieldMission)private r:Repository<FieldMission>,private scope:ScopePolicy,private audit:AuditService,private notes:NotificationService){}async create(d:any,u:AuthenticatedUser){await this.scope.assertCase(u,d.caseId);const entity = Object.assign(new FieldMission(), {...d,status:MissionStatus.ASSIGNED});const m: FieldMission=await this.r.save(entity);await this.notes.create(d.assignedOfficerId,'FIELD_MISSION','New field mission',d.whatToVerify,`/field/missions/${m.id}`);await this.audit.append('FIELD_MISSION_CREATED','FieldMission',m.id,d.caseId,u);return m;}list(u:AuthenticatedUser){return u.role===OfficerRole.FIELD_VERIFICATION_OFFICER?this.r.find({where:{assignedOfficerId:u.officerProfileId}}):this.r.find();}async submit(id:string,payload:Record<string,unknown>,u:AuthenticatedUser){const m=await this.r.findOneByOrFail({id});if(m.assignedOfficerId!==u.officerProfileId)throw new ForbiddenException();m.draftPayload=payload;m.status=MissionStatus.SUBMITTED;await this.r.save(m);await this.audit.append('FIELD_MISSION_SUBMITTED','FieldMission',id,m.caseId,u);return m;}}
class MissionDto{@IsUUID()caseId:string;@IsUUID()assignedOfficerId:string;@IsEnum(MissionType)type:MissionType;@IsString()whatToVerify:string;@IsString()whereToVerify:string;@IsString()whyRequired:string;@IsDateString()dueDate:string}class MissionSubmitDto{@IsObject()payload:Record<string,unknown>}
@Controller('missions')export class MissionController{constructor(private s:MissionService){}@Post()@Roles(OfficerRole.DISTRICT_RESTORATION_OFFICER,OfficerRole.TECHNICAL_RESTORATION_OFFICER)create(@Body()d:MissionDto,@CurrentUser()u:AuthenticatedUser){return this.s.create(d,u)}@Get()list(@CurrentUser()u:AuthenticatedUser){return this.s.list(u)}@Post(':id/submit')@Roles(OfficerRole.FIELD_VERIFICATION_OFFICER)submit(@Param('id')id:string,@Body()d:MissionSubmitDto,@CurrentUser()u:AuthenticatedUser){return this.s.submit(id,d.payload,u)}}

@Injectable()export class EvidenceService{constructor(@InjectRepository(EvidenceItem)private r:Repository<EvidenceItem>,@InjectRepository(FieldMission)private missions:Repository<FieldMission>,private scope:ScopePolicy,private audit:AuditService){}async add(missionId:string,d:any,u:AuthenticatedUser){const m=await this.missions.findOneByOrFail({id:missionId});if(m.assignedOfficerId!==u.officerProfileId)throw new ForbiddenException();const entity = Object.assign(new EvidenceItem(), {...d,caseId:m.caseId,missionId,submittedByProfileId:u.officerProfileId,status:EvidenceStatus.SUBMITTED,versionNumber:1});const e: EvidenceItem=await this.r.save(entity);await this.audit.append('EVIDENCE_SUBMITTED','EvidenceItem',e.id,e.caseId,u);return e;}async list(caseId:string,u:AuthenticatedUser){await this.scope.assertCase(u,caseId);return this.r.find({where:{caseId},order:{createdAt:'DESC'}})}async correct(id:string,payload:Record<string,unknown>,u:AuthenticatedUser){const old=await this.r.findOneByOrFail({id});if(old.submittedByProfileId!==u.officerProfileId)throw new ForbiddenException();old.status=EvidenceStatus.SUPERSEDED;await this.r.save(old);const next=await this.r.save(this.r.create({...old,id:undefined as any,payload,status:EvidenceStatus.SUBMITTED,versionNumber:old.versionNumber+1,supersedesEvidenceId:old.id}));await this.audit.append('EVIDENCE_CORRECTED','EvidenceItem',next.id,old.caseId,u);return next;}}
class EvidenceDto{@IsString()type:string;@IsString()source:string;@IsDateString()sourceDate:string;@IsObject()payload:Record<string,unknown>}class CorrectionDto{@IsObject()payload:Record<string,unknown>}
@Controller()export class EvidenceController{constructor(private s:EvidenceService){}@Post('missions/:missionId/evidence')@Roles(OfficerRole.FIELD_VERIFICATION_OFFICER)add(@Param('missionId')id:string,@Body()d:EvidenceDto,@CurrentUser()u:AuthenticatedUser){return this.s.add(id,d,u)}@Get('cases/:caseId/evidence')list(@Param('caseId')id:string,@CurrentUser()u:AuthenticatedUser){return this.s.list(id,u)}@Post('evidence/:id/corrections')correct(@Param('id')id:string,@Body()d:CorrectionDto,@CurrentUser()u:AuthenticatedUser){return this.s.correct(id,d.payload,u)}}

@Injectable()export class TechnicalService{constructor(@InjectRepository(TechnicalAssessment)private a:Repository<TechnicalAssessment>,@InjectRepository(TechnicalModule)private m:Repository<TechnicalModule>,@InjectRepository(EvidenceGap)private gaps:Repository<EvidenceGap>,private scope:ScopePolicy,private audit:AuditService){}async save(caseId:string,modules:any[],u:AuthenticatedUser){await this.scope.assertCase(u,caseId);let a=await this.a.findOne({where:{caseId,status:AssessmentStatus.DRAFT}});if(!a)a=await this.a.save(this.a.create({caseId,officerProfileId:u.officerProfileId,status:AssessmentStatus.DRAFT,versionNumber:1}));for(const x of modules){const existing=await this.m.findOne({where:{assessmentId:a.id,moduleType:x.moduleType}});const row: TechnicalModule=existing?Object.assign(existing,x):this.m.create({assessmentId:a.id,...x} as any);await this.m.save(row);}return{assessment:a,modules:await this.m.find({where:{assessmentId:a.id}})}}async submit(caseId:string,u:AuthenticatedUser){const a=await this.a.findOneByOrFail({caseId,status:AssessmentStatus.DRAFT});const modules=await this.m.find({where:{assessmentId:a.id}});const missing=Object.values(TechnicalModuleType).filter(t=>!modules.some(m=>m.moduleType===t&&m.complete));if(missing.length)throw new ForbiddenException(`Incomplete modules: ${missing.join(', ')}`);if(modules.some(m=>!m.supportingEvidenceIds.length))throw new ForbiddenException('Every module needs evidence links.');a.status=AssessmentStatus.SUBMITTED;await this.a.save(a);await this.audit.append('TECHNICAL_ASSESSMENT_SUBMITTED','TechnicalAssessment',a.id,caseId,u);return a;}async gap(caseId:string,d:any,u:AuthenticatedUser){await this.scope.assertCase(u,caseId);return this.gaps.save(this.gaps.create({caseId,createdByProfileId:u.officerProfileId,...d}));}}
class TechnicalSaveDto{@IsArray()modules:any[]}class GapDto{@IsString()description:string;@IsString()requiredEvidenceType:string;@IsBoolean()blocking:boolean}
@Controller('cases/:caseId')export class TechnicalController{constructor(private s:TechnicalService){}@Post('technical-assessment')@Roles(OfficerRole.TECHNICAL_RESTORATION_OFFICER)save(@Param('caseId')id:string,@Body()d:TechnicalSaveDto,@CurrentUser()u:AuthenticatedUser){return this.s.save(id,d.modules,u)}@Post('technical-assessment/submit')@Roles(OfficerRole.TECHNICAL_RESTORATION_OFFICER)submit(@Param('caseId')id:string,@CurrentUser()u:AuthenticatedUser){return this.s.submit(id,u)}@Post('evidence-gaps')@Roles(OfficerRole.TECHNICAL_RESTORATION_OFFICER,OfficerRole.DISTRICT_RESTORATION_OFFICER)gap(@Param('caseId')id:string,@Body()d:GapDto,@CurrentUser()u:AuthenticatedUser){return this.s.gap(id,d,u)}}

@Injectable()export class PlanService{constructor(@InjectRepository(PlanVersion)private r:Repository<PlanVersion>,private scope:ScopePolicy,private audit:AuditService,private workflow:WorkflowService){}async list(caseId:string,u:AuthenticatedUser){await this.scope.assertCase(u,caseId);return this.r.find({where:{caseId},order:{type:'ASC',versionNumber:'DESC'}})}async create(caseId:string,d:any,u:AuthenticatedUser){await this.scope.assertCase(u,caseId);const v=(await this.r.maximum('versionNumber',{caseId,type:d.type}))??0;return this.r.save(this.r.create({...d,caseId,versionNumber:v+1,status:PlanStatus.DRAFT,createdByProfileId:u.officerProfileId}));}async update(id:string,d:any,u:AuthenticatedUser){const p=await this.r.findOneByOrFail({id});await this.scope.assertCase(u,p.caseId);if(p.status!==PlanStatus.DRAFT)throw new ForbiddenException('Approved or submitted plans are immutable.');Object.assign(p,d,{id:p.id,caseId:p.caseId,status:p.status,versionNumber:p.versionNumber});return this.r.save(p)}async submit(id:string,u:AuthenticatedUser){const p=await this.r.findOneByOrFail({id});if(p.status!==PlanStatus.DRAFT)throw new ForbiddenException();p.status=PlanStatus.SUBMITTED;await this.r.save(p);await this.audit.append('PLAN_SUBMITTED','PlanVersion',id,p.caseId,u);return p;}async revise(id:string,u:AuthenticatedUser){const p=await this.r.findOneByOrFail({id});if(p.status!==PlanStatus.APPROVED)throw new ForbiddenException();return this.r.save(this.r.create({...p,id:undefined as any,status:PlanStatus.DRAFT,activeApproved:false,approvedByProfileId:null,approvalJustification:null,versionNumber:p.versionNumber+1,supersedesPlanId:p.id,createdByProfileId:u.officerProfileId}));}}
class PlanDto{@IsEnum(PlanType)type:PlanType;@IsString()objective:string;@IsString()costCategory:string;@IsString()duration:string;@IsArray()expectedBenefits:string[];@IsArray()risks:string[];@IsArray()assumptions:string[];@IsArray()evidenceLinks:string[];@IsArray()safeguards:string[];@IsObject()communityMaintenance:Record<string,unknown>;@IsArray()monitoringIndicators:string[]}
@Controller()export class PlanController{constructor(private s:PlanService){}@Get('cases/:caseId/plans')list(@Param('caseId')id:string,@CurrentUser()u:AuthenticatedUser){return this.s.list(id,u)}@Post('cases/:caseId/plans')@Roles(OfficerRole.TECHNICAL_RESTORATION_OFFICER)create(@Param('caseId')id:string,@Body()d:PlanDto,@CurrentUser()u:AuthenticatedUser){return this.s.create(id,d,u)}@Patch('plans/:id')@Roles(OfficerRole.TECHNICAL_RESTORATION_OFFICER)update(@Param('id')id:string,@Body()d:Partial<PlanDto>,@CurrentUser()u:AuthenticatedUser){return this.s.update(id,d,u)}@Post('plans/:id/submit')@Roles(OfficerRole.TECHNICAL_RESTORATION_OFFICER)submit(@Param('id')id:string,@CurrentUser()u:AuthenticatedUser){return this.s.submit(id,u)}@Post('plans/:id/revise')@Roles(OfficerRole.TECHNICAL_RESTORATION_OFFICER)revise(@Param('id')id:string,@CurrentUser()u:AuthenticatedUser){return this.s.revise(id,u)}}

@Injectable()export class ImplementationService{constructor(@InjectRepository(Milestone)private milestones:Repository<Milestone>,@InjectRepository(FieldObservation)private observations:Repository<FieldObservation>,@InjectRepository(PlanVersion)private plans:Repository<PlanVersion>,private scope:ScopePolicy,private audit:AuditService){}async createMilestone(caseId:string,d:any,u:AuthenticatedUser){await this.scope.assertCase(u,caseId);const plan=await this.plans.findOne({where:{caseId,status:PlanStatus.APPROVED,activeApproved:true}});if(!plan)throw new ForbiddenException('An approved plan is required.');return this.milestones.save(this.milestones.create({...d,caseId,approvedPlanId:plan.id,status:'NOT_STARTED'}));}async observe(id:string,d:any,u:AuthenticatedUser){const m=await this.milestones.findOneByOrFail({id});await this.scope.assertCase(u,m.caseId);const entity = Object.assign(new FieldObservation(), {...d,caseId:m.caseId,milestoneId:id,submittedByProfileId:u.officerProfileId});const o: FieldObservation=await this.observations.save(entity);await this.audit.append('FIELD_PROGRESS_SUBMITTED','FieldObservation',o.id,m.caseId,u,{deviationCategory:d.deviationCategory});return o;}}
class MilestoneDto{@IsString()activity:string;@IsString()expectedOutput:string;@IsDateString()dueDate:string}class ObservationDto{@IsOptional()@IsNumber()@Min(0)@Max(100)progressPercentage?:number;@IsString()notes:string;@IsEnum(DeviationCategory)deviationCategory:DeviationCategory;@IsArray()evidenceIds:string[]}
@Controller()export class ImplementationController{constructor(private s:ImplementationService){}@Post('cases/:caseId/milestones')@Roles(OfficerRole.DISTRICT_RESTORATION_OFFICER)create(@Param('caseId')id:string,@Body()d:MilestoneDto,@CurrentUser()u:AuthenticatedUser){return this.s.createMilestone(id,d,u)}@Post('milestones/:id/observations')@Roles(OfficerRole.FIELD_VERIFICATION_OFFICER)observe(@Param('id')id:string,@Body()d:ObservationDto,@CurrentUser()u:AuthenticatedUser){return this.s.observe(id,d,u)}}

@Injectable()export class MonitoringService{constructor(@InjectRepository(MonitoringEvent)private r:Repository<MonitoringEvent>,private scope:ScopePolicy,private audit:AuditService){}async add(caseId:string,d:any,u:AuthenticatedUser){await this.scope.assertCase(u,caseId);const entity = Object.assign(new MonitoringEvent(), {...d,caseId,submittedByProfileId:u.officerProfileId});const x: MonitoringEvent=await this.r.save(entity);await this.audit.append('MONITORING_OBSERVATION_SUBMITTED','MonitoringEvent',x.id,caseId,u);return x;}async list(caseId:string,u:AuthenticatedUser){await this.scope.assertCase(u,caseId);return this.r.find({where:{caseId},order:{observedAt:'DESC'}})}}
class MonitoringDto{@IsDateString()observedAt:string;@IsObject()indicators:Record<string,unknown>;@IsBoolean()blockingIssue:boolean}
@Controller('cases/:caseId/monitoring')export class MonitoringController{constructor(private s:MonitoringService){}@Post()@Roles(OfficerRole.FIELD_VERIFICATION_OFFICER,OfficerRole.TECHNICAL_RESTORATION_OFFICER)add(@Param('caseId')id:string,@Body()d:MonitoringDto,@CurrentUser()u:AuthenticatedUser){return this.s.add(id,d,u)}@Get()list(@Param('caseId')id:string,@CurrentUser()u:AuthenticatedUser){return this.s.list(id,u)}}

@Controller('notifications')export class NotificationController{constructor(private s:NotificationService){}@Get()list(@CurrentUser()u:AuthenticatedUser){return this.s.list(u.officerProfileId)}@Post(':id/read')read(@Param('id')id:string,@CurrentUser()u:AuthenticatedUser){return this.s.read(id,u.officerProfileId)}}
@Controller('audit')@Roles(OfficerRole.SYSTEM_ADMINISTRATOR)export class AuditController{constructor(private s:AuditService){}@Get()list(){return this.s.list()}}

@Module({imports:[TypeOrmModule.forFeature([User,OfficerProfile,Region,PrioritySignal,SignalDecision,LandPatch,RestorationCase,CaseAssignment,FieldMission,EvidenceItem,EvidenceGap,TechnicalAssessment,TechnicalModule,PlanVersion,Milestone,FieldObservation,MonitoringEvent,Notification,AuditEvent])],providers:[AuditService,NotificationService,UserService,RegionService,SignalService,LandService,CaseService,MissionService,EvidenceService,TechnicalService,PlanService,ImplementationService,MonitoringService],controllers:[UserController,RegionController,SignalController,LandController,CaseController,MissionController,EvidenceController,TechnicalController,PlanController,ImplementationController,MonitoringController,NotificationController,AuditController],exports:[AuditService,NotificationService]})export class DomainModule{}


