import { Column, CreateDateColumn, Entity, Index, PrimaryGeneratedColumn, Unique, UpdateDateColumn, VersionColumn } from 'typeorm';
import { AIProposalStatus, AssessmentStatus, AssignmentStatus, CaseStatus, DeviationCategory, EvidenceStatus, MissionStatus, MissionType, OfficerRole, PlanStatus, PlanType, SignalStatus, TaskPriority, TaskStatus, TechnicalModuleType } from './common';
abstract class Base { @PrimaryGeneratedColumn('uuid') id:string; @CreateDateColumn() createdAt:Date; @UpdateDateColumn() updatedAt:Date; }
@Entity('users') export class User extends Base { @Index({unique:true}) @Column() email:string; @Column() passwordHash:string; @Column({default:true}) isActive:boolean; }
@Entity('officer_profiles') export class OfficerProfile extends Base { @Column('uuid',{unique:true,nullable:true}) userId?:string|null; @Index({unique:true}) @Column('uuid',{unique:true,nullable:true}) authUserId?:string|null; @Index() @Column({type:'varchar',nullable:true}) email?:string|null; @Column() fullName:string; @Column() role:OfficerRole; @Column({default:true}) active:boolean; @Column('uuid',{nullable:true}) stateId?:string|null; @Column('uuid',{nullable:true}) districtId?:string|null; }
@Entity('refresh_tokens') export class RefreshToken extends Base { @Column('uuid') userId:string; @Column() tokenHash:string; @Column('timestamptz') expiresAt:Date; @Column('timestamptz',{nullable:true}) revokedAt?:Date|null; }
@Entity('regions') export class Region extends Base { @Column() name:string; @Column() type:string; @Column('uuid',{nullable:true}) parentId?:string|null; @Column({nullable:true}) code?:string; }
@Entity('priority_signals') export class PrioritySignal extends Base { @Column('uuid') stateId:string; @Column('uuid',{nullable:true}) districtId?:string|null; @Column('decimal',{precision:6,scale:2}) priorityScore:number; @Column('jsonb') scoreBreakdown:Record<string,number>; @Column() reason:string; @Column('jsonb',{default:{}}) availableEvidence:Record<string,unknown>; @Column('jsonb',{default:{}}) missingEvidence:Record<string,unknown>; @Column() source:string; @Column('date') sourceDate:string; @Column() status:SignalStatus; @Column('uuid',{nullable:true}) assignedDistrictOfficerId?:string|null; }
@Entity('signal_decisions') export class SignalDecision extends Base { @Column('uuid') signalId:string; @Column('uuid') actorProfileId:string; @Column() decision:string; @Column() justification:string; @Column('uuid',{nullable:true}) districtId?:string|null; @Column('uuid',{nullable:true}) districtOfficerId?:string|null; }
@Entity('land_patches') export class LandPatch extends Base { @Column('uuid') createdByProfileId:string; @Column('uuid') districtId:string; @Column('uuid') mandalId:string; @Column('uuid') villageId:string; @Column('jsonb') geometry:Record<string,unknown>; @Column('decimal',{precision:14,scale:4}) areaHectares:number; @Column('decimal',{precision:14,scale:2}) perimeterMetres:number; @Column('jsonb') centroid:Record<string,unknown>; @Column('jsonb') boundingBox:number[]; @Index() @Column() polygonHash:string; @Column({default:false}) valid:boolean; @Column('jsonb',{default:[]}) warnings:string[]; }
@Entity('restoration_cases') export class RestorationCase extends Base { @Column('uuid') signalId:string; @Column('uuid') landPatchId:string; @Column('uuid') districtOfficerId:string; @Column() title:string; @Column() objective:string; @Index() @Column() status:CaseStatus; @VersionColumn() version:number; @Column({default:false}) implementationAccepted:boolean; @Column({default:false}) outcomeVerified:boolean; }
@Entity('case_assignments') @Unique(['caseId','officerProfileId','assignmentType']) export class CaseAssignment extends Base { @Column('uuid') caseId:string; @Column('uuid') officerProfileId:string; @Column() role:OfficerRole; @Column() assignmentType:string; @Column({default:true}) active:boolean; }
@Entity('field_missions') export class FieldMission extends Base { @Column('uuid') caseId:string; @Index() @Column('uuid') assignedOfficerId:string; @Column() type:MissionType; @Column() status:MissionStatus; @Column() whatToVerify:string; @Column() whereToVerify:string; @Column() whyRequired:string; @Column('date') dueDate:string; @Column('jsonb',{default:{}}) draftPayload:Record<string,unknown>; @VersionColumn() version:number; }
@Entity('evidence_items') export class EvidenceItem extends Base { @Index() @Column('uuid',{nullable:true}) caseId?:string|null; @Column('uuid',{nullable:true}) missionId?:string|null; @Index() @Column('uuid',{nullable:true}) taskId?:string|null; @Index() @Column('uuid',{nullable:true}) assignmentId?:string|null; @Column() type:string; @Column() status:EvidenceStatus; @Column({type:'varchar',nullable:true}) source?:string|null; @Column('date',{nullable:true}) sourceDate?:string|null; @Column('uuid') submittedByProfileId:string; @Column({type:'text',nullable:true}) description?:string|null; @Column({type:'varchar',nullable:true}) storagePath?:string|null; @Column('decimal',{precision:10,scale:7,nullable:true}) latitude?:number|null; @Column('decimal',{precision:10,scale:7,nullable:true}) longitude?:number|null; @Column('timestamptz',{nullable:true}) capturedAt?:Date|null; @Column('jsonb',{default:{}}) metadata:Record<string,unknown>; @Column('jsonb',{default:{}}) payload:Record<string,unknown>; @Column({default:1}) versionNumber:number; @Column('uuid',{nullable:true}) supersedesEvidenceId?:string|null; }
@Entity('evidence_gaps') export class EvidenceGap extends Base { @Column('uuid') caseId:string; @Column('uuid') createdByProfileId:string; @Column() description:string; @Column() requiredEvidenceType:string; @Column({default:true}) blocking:boolean; @Column({default:false}) resolved:boolean; }
@Entity('technical_assessments') export class TechnicalAssessment extends Base { @Column('uuid') caseId:string; @Column('uuid') officerProfileId:string; @Column() status:AssessmentStatus; @Column({default:1}) versionNumber:number; @VersionColumn() recordVersion:number; }
@Entity('technical_modules') @Unique(['assessmentId','moduleType']) export class TechnicalModule extends Base { @Column('uuid') assessmentId:string; @Column() moduleType:TechnicalModuleType; @Column('jsonb') data:Record<string,unknown>; @Column('jsonb',{default:[]}) supportingEvidenceIds:string[]; @Column({default:false}) complete:boolean; }
@Entity('plan_versions') export class PlanVersion extends Base { @Index() @Column('uuid') caseId:string; @Column() type:PlanType; @Column() status:PlanStatus; @Column() versionNumber:number; @VersionColumn() recordVersion:number; @Column() objective:string; @Column() costCategory:string; @Column() duration:string; @Column('jsonb',{default:[]}) expectedBenefits:string[]; @Column('jsonb',{default:[]}) risks:string[]; @Column('jsonb',{default:[]}) assumptions:string[]; @Column('jsonb',{default:[]}) evidenceLinks:string[]; @Column('jsonb',{default:[]}) safeguards:string[]; @Column('jsonb',{default:{}}) communityMaintenance:Record<string,unknown>; @Column('jsonb',{default:[]}) monitoringIndicators:string[]; @Column('uuid') createdByProfileId:string; @Column('uuid',{nullable:true}) approvedByProfileId?:string|null; @Column({type:'text',nullable:true}) approvalJustification?:string|null; @Column({default:false}) activeApproved:boolean; @Column('uuid',{nullable:true}) supersedesPlanId?:string|null; }
@Entity('milestones') export class Milestone extends Base { @Column('uuid') caseId:string; @Column('uuid') approvedPlanId:string; @Column() activity:string; @Column() expectedOutput:string; @Column('date') dueDate:string; @Column() status:string; @VersionColumn() version:number; }
@Entity('field_observations') export class FieldObservation extends Base { @Column('uuid') caseId:string; @Column('uuid',{nullable:true}) milestoneId?:string|null; @Column('uuid') submittedByProfileId:string; @Column('decimal',{precision:5,scale:2,nullable:true}) progressPercentage?:number|null; @Column() notes:string; @Column() deviationCategory:DeviationCategory; @Column('jsonb',{default:[]}) evidenceIds:string[]; }
@Entity('monitoring_events') export class MonitoringEvent extends Base { @Column('uuid') caseId:string; @Column('uuid') submittedByProfileId:string; @Column('date') observedAt:string; @Column('jsonb') indicators:Record<string,unknown>; @Column({default:false}) blockingIssue:boolean; }
@Entity('notifications') export class Notification extends Base { @Column('uuid') recipientProfileId:string; @Column() type:string; @Column() title:string; @Column() message:string; @Column({nullable:true}) deepLink?:string; @Column('timestamptz',{nullable:true}) readAt?:Date|null; }
@Entity('audit_events') export class AuditEvent extends Base { @Column('uuid',{nullable:true}) actorProfileId?:string|null; @Column({type:'varchar',nullable:true}) actorRole?:OfficerRole|null; @Column() action:string; @Column() targetType:string; @Column('uuid',{nullable:true}) targetId?:string|null; @Column('uuid',{nullable:true}) caseId?:string|null; @Index() @Column('uuid',{nullable:true}) assignmentId?:string|null; @Column({nullable:true}) justification?:string; @Column('jsonb',{default:{}}) metadata:Record<string,unknown>; }
@Entity('ai_action_proposals') export class AIActionProposal extends Base { @Column('uuid') createdByProfileId:string; @Column('uuid',{nullable:true}) caseId?:string|null; @Column() actionType:string; @Column('jsonb') previewPayload:Record<string,unknown>; @Column() status:AIProposalStatus; @VersionColumn() version:number; @Column('timestamptz') expiresAt:Date; }
@Entity('restoration_projects') export class RestorationProject extends Base { @Column() name:string; @Column({type:'text',nullable:true}) description?:string|null; @Index() @Column('uuid',{nullable:true}) districtId?:string|null; @Index() @Column() status:string; @Column('uuid') createdByProfileId:string; }
@Entity('land_sectors') export class LandSector extends Base { @Index() @Column('uuid') projectId:string; @Column() name:string; @Column({type:'varchar',nullable:true}) villageName?:string|null; @Column({type:'varchar',nullable:true}) mandalName?:string|null; @Column({type:'varchar',nullable:true}) districtName?:string|null; @Column('decimal',{precision:14,scale:4}) areaHectares:number; @Column('jsonb') geometry:Record<string,unknown>; @Column('jsonb',{nullable:true}) centroid?:Record<string,unknown>|null; @Index() @Column() status:string; }
@Entity('officer_assignments') export class OfficerAssignment extends Base { @Index() @Column('uuid') projectId:string; @Index() @Column('uuid',{nullable:true}) sectorId?:string|null; @Index() @Column('uuid') assignedToProfileId:string; @Column('uuid') assignedByProfileId:string; @Column() assignmentType:string; @Index() @Column() status:AssignmentStatus; @Column('date',{nullable:true}) startDate?:string|null; @Index() @Column('date',{nullable:true}) dueDate?:string|null; @Column({type:'text',nullable:true}) instructions?:string|null; }
@Entity('field_tasks') export class FieldTask extends Base { @Index() @Column('uuid') assignmentId:string; @Column() title:string; @Column({type:'text',nullable:true}) description?:string|null; @Column() taskType:string; @Index() @Column() priority:TaskPriority; @Index() @Column() status:TaskStatus; @Index() @Column('timestamptz',{nullable:true}) dueAt?:Date|null; @Column({default:false}) requiresEvidence:boolean; @Column('uuid') createdByProfileId:string; @Index() @Column('uuid') assignedToProfileId:string; }
@Entity('field_reports') export class FieldReport extends Base { @Index() @Column('uuid') taskId:string; @Index() @Column('uuid') assignmentId:string; @Index() @Column('uuid') submittedByProfileId:string; @Column() reportType:string; @Column({type:'text'}) notes:string; @Column({type:'varchar',nullable:true}) changeCategory?:string|null; @Column('decimal',{precision:10,scale:7,nullable:true}) latitude?:number|null; @Column('decimal',{precision:10,scale:7,nullable:true}) longitude?:number|null; @Column('jsonb',{default:{}}) payload:Record<string,unknown>; @CreateDateColumn({type:'timestamptz'}) submittedAt:Date; }

export const ENTITIES=[User,OfficerProfile,RefreshToken,Region,PrioritySignal,SignalDecision,LandPatch,RestorationCase,CaseAssignment,FieldMission,EvidenceItem,EvidenceGap,TechnicalAssessment,TechnicalModule,PlanVersion,Milestone,FieldObservation,MonitoringEvent,Notification,AuditEvent,AIActionProposal,RestorationProject,LandSector,OfficerAssignment,FieldTask,FieldReport];

