import { Body, Controller, ForbiddenException, Get, Injectable, Module, NotFoundException, Param, Post } from '@nestjs/common';
import { InjectDataSource, InjectRepository, TypeOrmModule } from '@nestjs/typeorm';
import { DataSource, Repository } from 'typeorm';
import { IsEnum, IsInt, IsOptional, IsString, IsUUID, Min } from 'class-validator';
import { ApiException, AuthenticatedUser, CaseStatus, CurrentUser, ErrorCode, EvidenceStatus, MissionStatus, OfficerRole, PlanStatus, PlanType, Roles } from './common';
import { AuditEvent, EvidenceGap, EvidenceItem, FieldMission, LandPatch, Milestone, MonitoringEvent, PlanVersion, RestorationCase, TechnicalAssessment, TechnicalModule } from './entities';
import { ScopePolicy } from './database';

export const CASE_TRANSITIONS:Record<CaseStatus,CaseStatus[]>={
  REGIONAL_SIGNAL:[CaseStatus.SIGNAL_ACCEPTED,CaseStatus.SIGNAL_DISMISSED],SIGNAL_ACCEPTED:[CaseStatus.LAND_PATCH_DRAFT],SIGNAL_DISMISSED:[],
  LAND_PATCH_DRAFT:[CaseStatus.CASE_OPEN],CASE_OPEN:[CaseStatus.FIELD_VERIFICATION_ASSIGNED],FIELD_VERIFICATION_ASSIGNED:[CaseStatus.FIELD_VERIFIED],
  FIELD_VERIFIED:[CaseStatus.TECHNICAL_REVIEW],TECHNICAL_REVIEW:[CaseStatus.EVIDENCE_REQUIRED,CaseStatus.PLAN_READY],EVIDENCE_REQUIRED:[CaseStatus.FIELD_VERIFICATION_ASSIGNED],
  PLAN_READY:[CaseStatus.PLAN_UNDER_REVIEW],PLAN_UNDER_REVIEW:[CaseStatus.TECHNICAL_REVIEW,CaseStatus.PLAN_APPROVED],PLAN_APPROVED:[CaseStatus.IMPLEMENTATION],
  IMPLEMENTATION:[CaseStatus.VERIFICATION_SUBMITTED],VERIFICATION_SUBMITTED:[CaseStatus.CORRECTION_REQUIRED,CaseStatus.MONITORING],CORRECTION_REQUIRED:[CaseStatus.IMPLEMENTATION],
  MONITORING:[CaseStatus.TECHNICAL_REVIEW,CaseStatus.OUTCOME_REVIEW],OUTCOME_REVIEW:[CaseStatus.MONITORING,CaseStatus.CLOSED],CLOSED:[CaseStatus.ARCHIVED],ARCHIVED:[],
};
const OWNERS:Partial<Record<CaseStatus,OfficerRole[]>>={
  CASE_OPEN:[OfficerRole.DISTRICT_RESTORATION_OFFICER],FIELD_VERIFICATION_ASSIGNED:[OfficerRole.DISTRICT_RESTORATION_OFFICER],FIELD_VERIFIED:[OfficerRole.DISTRICT_RESTORATION_OFFICER],
  TECHNICAL_REVIEW:[OfficerRole.DISTRICT_RESTORATION_OFFICER,OfficerRole.TECHNICAL_RESTORATION_OFFICER],EVIDENCE_REQUIRED:[OfficerRole.DISTRICT_RESTORATION_OFFICER,OfficerRole.TECHNICAL_RESTORATION_OFFICER],
  PLAN_READY:[OfficerRole.TECHNICAL_RESTORATION_OFFICER],PLAN_UNDER_REVIEW:[OfficerRole.TECHNICAL_RESTORATION_OFFICER,OfficerRole.DISTRICT_RESTORATION_OFFICER],PLAN_APPROVED:[OfficerRole.DISTRICT_RESTORATION_OFFICER],
  IMPLEMENTATION:[OfficerRole.DISTRICT_RESTORATION_OFFICER],VERIFICATION_SUBMITTED:[OfficerRole.FIELD_VERIFICATION_OFFICER],CORRECTION_REQUIRED:[OfficerRole.DISTRICT_RESTORATION_OFFICER],
  MONITORING:[OfficerRole.DISTRICT_RESTORATION_OFFICER],OUTCOME_REVIEW:[OfficerRole.DISTRICT_RESTORATION_OFFICER],CLOSED:[OfficerRole.DISTRICT_RESTORATION_OFFICER],ARCHIVED:[OfficerRole.DISTRICT_RESTORATION_OFFICER],
};
@Injectable()
export class DecisionGateService{
  constructor(@InjectRepository(LandPatch)private patches:Repository<LandPatch>,@InjectRepository(FieldMission)private missions:Repository<FieldMission>,@InjectRepository(EvidenceItem)private evidence:Repository<EvidenceItem>,@InjectRepository(EvidenceGap)private gaps:Repository<EvidenceGap>,@InjectRepository(TechnicalAssessment)private assessments:Repository<TechnicalAssessment>,@InjectRepository(TechnicalModule)private modules:Repository<TechnicalModule>,@InjectRepository(PlanVersion)private plans:Repository<PlanVersion>,@InjectRepository(Milestone)private milestones:Repository<Milestone>,@InjectRepository(MonitoringEvent)private monitoring:Repository<MonitoringEvent>){}
  async evidenceDebt(caseId:string){const gaps=await this.gaps.find({where:{caseId,resolved:false}});const unverified=await this.evidence.count({where:{caseId,status:EvidenceStatus.SUBMITTED}});const a=await this.assessments.findOne({where:{caseId,status:'DRAFT' as any},order:{versionNumber:'DESC'}});const modules=a?await this.modules.find({where:{assessmentId:a.id}}):[];const missing=Object.values(require('./common').TechnicalModuleType).filter((x:any)=>!modules.some(m=>m.moduleType===x&&m.complete));const blocking=[...gaps.filter(g=>g.blocking).map(g=>g.description),...missing.map((x:any)=>`Missing module: ${x}`)];return{level:blocking.length?'BLOCKING':unverified?'MODERATE':'LOW',blocking:!!blocking.length,missingItems:blocking,unverified,evaluatedAt:new Date().toISOString(),rulesVersion:'1.0'};}
  async evaluate(c:RestorationCase,next:CaseStatus,context:{reason?:string;selectedPlanId?:string}){const issues:string[]=[];
    if(next===CaseStatus.CASE_OPEN){const p=await this.patches.findOne({where:{id:c.landPatchId}});if(!p?.valid)issues.push('A valid land patch is required.');if(!c.objective.trim())issues.push('Objective is required.');}
    if(next===CaseStatus.FIELD_VERIFIED){if(!await this.missions.exist({where:{caseId:c.id,status:MissionStatus.SUBMITTED}}))issues.push('A submitted targeted mission is required.');if(!await this.evidence.exist({where:{caseId:c.id}}))issues.push('Field evidence is required.');}
    if(next===CaseStatus.PLAN_READY){if(!await this.assessments.exist({where:{caseId:c.id,status:'SUBMITTED' as any}}))issues.push('A submitted assessment is required.');if((await this.evidenceDebt(c.id)).blocking)issues.push('Blocking Evidence Debt must be resolved.');}
    if(next===CaseStatus.PLAN_UNDER_REVIEW){const plans=await this.plans.find({where:{caseId:c.id,status:PlanStatus.SUBMITTED}});for(const t of Object.values(PlanType))if(!plans.some(p=>p.type===t))issues.push(`${t} must be submitted.`);}
    if(next===CaseStatus.PLAN_APPROVED){if(!context.selectedPlanId)issues.push('Selected plan is required.');if(!context.reason?.trim())issues.push('Approval justification is required.');if((await this.evidenceDebt(c.id)).blocking)issues.push('Blocking Evidence Debt must be resolved.');}
    if(next===CaseStatus.VERIFICATION_SUBMITTED&&!await this.milestones.exist({where:{caseId:c.id}}))issues.push('Milestones are required.');
    if(next===CaseStatus.MONITORING&&!context.reason?.trim())issues.push('Implementation acceptance reason is required.');
    if(next===CaseStatus.CLOSED){if(!await this.monitoring.exist({where:{caseId:c.id}}))issues.push('Monitoring evidence is required.');if(!context.reason?.trim())issues.push('Closure justification is required.');}
    return{gate:`${c.status}_TO_${next}`,passed:!issues.length,blockingIssues:issues,warnings:[],requiredActions:issues,evaluatedAt:new Date().toISOString(),rulesVersion:'1.0'};
  }
}
@Injectable()
export class WorkflowService{
  constructor(private scope:ScopePolicy,private gates:DecisionGateService,@InjectDataSource()private db:DataSource){}
  allowed(status:CaseStatus){return CASE_TRANSITIONS[status];}
  async transition(caseId:string,input:{nextStatus:CaseStatus;expectedVersion:number;reason?:string;selectedPlanId?:string},user:AuthenticatedUser){await this.scope.assertCase(user,caseId);const owners=OWNERS[input.nextStatus];if(owners&&!owners.includes(user.role))throw new ForbiddenException('This role does not own the transition.');return this.db.transaction(async manager=>{const c=await manager.findOne(RestorationCase,{where:{id:caseId},lock:{mode:'pessimistic_write'}});if(!c)throw new NotFoundException();if(c.version!==input.expectedVersion)throw new ApiException(ErrorCode.VERSION_CONFLICT,'Case version changed.',409);if(!CASE_TRANSITIONS[c.status].includes(input.nextStatus))throw new ApiException(ErrorCode.INVALID_TRANSITION,`Cannot transition ${c.status} to ${input.nextStatus}.`,409);const gate=await this.gates.evaluate(c,input.nextStatus,input);if(!gate.passed)throw new ApiException(ErrorCode.GATE_BLOCKED,'Decision gate blocked the transition.',422,gate);const from=c.status;c.status=input.nextStatus;if(input.nextStatus===CaseStatus.MONITORING)c.implementationAccepted=true;if(input.nextStatus===CaseStatus.CLOSED)c.outcomeVerified=true;if(input.nextStatus===CaseStatus.PLAN_APPROVED){const selected=await manager.findOne(PlanVersion,{where:{id:input.selectedPlanId,caseId,status:PlanStatus.SUBMITTED},lock:{mode:'pessimistic_write'}});if(!selected)throw new ApiException(ErrorCode.GATE_BLOCKED,'Selected submitted plan not found.',422);await manager.update(PlanVersion,{caseId,activeApproved:true},{activeApproved:false,status:PlanStatus.SUPERSEDED});selected.status=PlanStatus.APPROVED;selected.activeApproved=true;selected.approvedByProfileId=user.officerProfileId;selected.approvalJustification=input.reason;await manager.save(selected);}const saved=await manager.save(c);await manager.save(AuditEvent,manager.create(AuditEvent,{actorProfileId:user.officerProfileId,actorRole:user.role,action:'CASE_TRANSITION',targetType:'RestorationCase',targetId:caseId,caseId,justification:input.reason,metadata:{from,to:input.nextStatus,gate}}));return{case:saved,gate};});}
}
class TransitionDto{@IsEnum(CaseStatus)nextStatus:CaseStatus;@IsInt()@Min(1)expectedVersion:number;@IsOptional()@IsString()reason?:string;@IsOptional()@IsUUID()selectedPlanId?:string}
@Controller('cases')export class WorkflowController{constructor(private workflow:WorkflowService,@InjectRepository(RestorationCase)private cases:Repository<RestorationCase>){}@Get(':id/allowed-transitions')async allowed(@Param('id')id:string){const c=await this.cases.findOneByOrFail({id});return{currentStatus:c.status,allowed:this.workflow.allowed(c.status)}}@Post(':id/transition')transition(@Param('id')id:string,@Body()d:TransitionDto,@CurrentUser()u:AuthenticatedUser){return this.workflow.transition(id,d,u)}}
@Module({imports:[TypeOrmModule.forFeature([LandPatch,FieldMission,EvidenceItem,EvidenceGap,TechnicalAssessment,TechnicalModule,PlanVersion,Milestone,MonitoringEvent,RestorationCase,AuditEvent])],providers:[DecisionGateService,WorkflowService],controllers:[WorkflowController],exports:[DecisionGateService,WorkflowService]})export class WorkflowModule{}
