import { MigrationInterface, QueryRunner } from 'typeorm';
export class InitialSchema1722000000000 implements MigrationInterface{
  async up(q:QueryRunner){await q.query(`CREATE EXTENSION IF NOT EXISTS "pgcrypto";`);await q.query(`
CREATE TABLE users(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),email varchar UNIQUE NOT NULL,password_hash varchar NOT NULL,is_active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE officer_profiles(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid UNIQUE NOT NULL REFERENCES users(id),full_name varchar NOT NULL,role varchar NOT NULL,state_id uuid,district_id uuid,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE refresh_tokens(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES users(id),token_hash varchar NOT NULL,expires_at timestamptz NOT NULL,revoked_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE regions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name varchar NOT NULL,type varchar NOT NULL,parent_id uuid REFERENCES regions(id),code varchar,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE officer_profiles ADD CONSTRAINT fk_profile_state FOREIGN KEY(state_id) REFERENCES regions(id);ALTER TABLE officer_profiles ADD CONSTRAINT fk_profile_district FOREIGN KEY(district_id) REFERENCES regions(id);
CREATE TABLE priority_signals(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),state_id uuid NOT NULL REFERENCES regions(id),district_id uuid REFERENCES regions(id),priority_score decimal(6,2) NOT NULL,score_breakdown jsonb NOT NULL,reason varchar NOT NULL,available_evidence jsonb NOT NULL DEFAULT '{}',missing_evidence jsonb NOT NULL DEFAULT '{}',source varchar NOT NULL,source_date date NOT NULL,status varchar NOT NULL,assigned_district_officer_id uuid REFERENCES officer_profiles(id),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE signal_decisions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),signal_id uuid NOT NULL REFERENCES priority_signals(id),actor_profile_id uuid NOT NULL REFERENCES officer_profiles(id),decision varchar NOT NULL,justification varchar NOT NULL,district_id uuid REFERENCES regions(id),district_officer_id uuid REFERENCES officer_profiles(id),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE land_patches(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),created_by_profile_id uuid NOT NULL REFERENCES officer_profiles(id),district_id uuid NOT NULL REFERENCES regions(id),mandal_id uuid NOT NULL REFERENCES regions(id),village_id uuid NOT NULL REFERENCES regions(id),geometry jsonb NOT NULL,area_hectares decimal(14,4) NOT NULL,perimeter_metres decimal(14,2) NOT NULL,centroid jsonb NOT NULL,bounding_box jsonb NOT NULL,polygon_hash varchar NOT NULL,valid boolean NOT NULL DEFAULT false,warnings jsonb NOT NULL DEFAULT '[]',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE restoration_cases(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),signal_id uuid NOT NULL REFERENCES priority_signals(id),land_patch_id uuid NOT NULL REFERENCES land_patches(id),district_officer_id uuid NOT NULL REFERENCES officer_profiles(id),title varchar NOT NULL,objective varchar NOT NULL,status varchar NOT NULL,version integer NOT NULL DEFAULT 1,implementation_accepted boolean NOT NULL DEFAULT false,outcome_verified boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE case_assignments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),case_id uuid NOT NULL REFERENCES restoration_cases(id),officer_profile_id uuid NOT NULL REFERENCES officer_profiles(id),role varchar NOT NULL,assignment_type varchar NOT NULL,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(case_id,officer_profile_id,assignment_type));
CREATE TABLE field_missions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),case_id uuid NOT NULL REFERENCES restoration_cases(id),assigned_officer_id uuid NOT NULL REFERENCES officer_profiles(id),type varchar NOT NULL,status varchar NOT NULL,what_to_verify varchar NOT NULL,where_to_verify varchar NOT NULL,why_required varchar NOT NULL,due_date date NOT NULL,draft_payload jsonb NOT NULL DEFAULT '{}',version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE evidence_items(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),case_id uuid NOT NULL REFERENCES restoration_cases(id),mission_id uuid NOT NULL REFERENCES field_missions(id),type varchar NOT NULL,status varchar NOT NULL,source varchar NOT NULL,source_date date NOT NULL,submitted_by_profile_id uuid NOT NULL REFERENCES officer_profiles(id),payload jsonb NOT NULL DEFAULT '{}',version_number integer NOT NULL DEFAULT 1,supersedes_evidence_id uuid REFERENCES evidence_items(id),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE evidence_gaps(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),case_id uuid NOT NULL REFERENCES restoration_cases(id),created_by_profile_id uuid NOT NULL REFERENCES officer_profiles(id),description varchar NOT NULL,required_evidence_type varchar NOT NULL,blocking boolean NOT NULL DEFAULT true,resolved boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE technical_assessments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),case_id uuid NOT NULL REFERENCES restoration_cases(id),officer_profile_id uuid NOT NULL REFERENCES officer_profiles(id),status varchar NOT NULL,version_number integer NOT NULL DEFAULT 1,record_version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE technical_modules(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),assessment_id uuid NOT NULL REFERENCES technical_assessments(id),module_type varchar NOT NULL,data jsonb NOT NULL,supporting_evidence_ids jsonb NOT NULL DEFAULT '[]',complete boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(assessment_id,module_type));
CREATE TABLE plan_versions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),case_id uuid NOT NULL REFERENCES restoration_cases(id),type varchar NOT NULL,status varchar NOT NULL,version_number integer NOT NULL,record_version integer NOT NULL DEFAULT 1,objective varchar NOT NULL,cost_category varchar NOT NULL,duration varchar NOT NULL,expected_benefits jsonb NOT NULL DEFAULT '[]',risks jsonb NOT NULL DEFAULT '[]',assumptions jsonb NOT NULL DEFAULT '[]',evidence_links jsonb NOT NULL DEFAULT '[]',safeguards jsonb NOT NULL DEFAULT '[]',community_maintenance jsonb NOT NULL DEFAULT '{}',monitoring_indicators jsonb NOT NULL DEFAULT '[]',created_by_profile_id uuid NOT NULL REFERENCES officer_profiles(id),approved_by_profile_id uuid REFERENCES officer_profiles(id),approval_justification varchar,active_approved boolean NOT NULL DEFAULT false,supersedes_plan_id uuid REFERENCES plan_versions(id),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX one_active_approved_plan_per_case ON plan_versions(case_id) WHERE active_approved=true;
CREATE TABLE milestones(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),case_id uuid NOT NULL REFERENCES restoration_cases(id),approved_plan_id uuid NOT NULL REFERENCES plan_versions(id),activity varchar NOT NULL,expected_output varchar NOT NULL,due_date date NOT NULL,status varchar NOT NULL,version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE field_observations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),case_id uuid NOT NULL REFERENCES restoration_cases(id),milestone_id uuid REFERENCES milestones(id),submitted_by_profile_id uuid NOT NULL REFERENCES officer_profiles(id),progress_percentage decimal(5,2),notes varchar NOT NULL,deviation_category varchar NOT NULL,evidence_ids jsonb NOT NULL DEFAULT '[]',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE monitoring_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),case_id uuid NOT NULL REFERENCES restoration_cases(id),submitted_by_profile_id uuid NOT NULL REFERENCES officer_profiles(id),observed_at date NOT NULL,indicators jsonb NOT NULL,blocking_issue boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE notifications(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),recipient_profile_id uuid NOT NULL REFERENCES officer_profiles(id),type varchar NOT NULL,title varchar NOT NULL,message varchar NOT NULL,deep_link varchar,read_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE audit_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),actor_profile_id uuid REFERENCES officer_profiles(id),actor_role varchar,action varchar NOT NULL,target_type varchar NOT NULL,target_id uuid,case_id uuid REFERENCES restoration_cases(id),justification varchar,metadata jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE ai_action_proposals(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),created_by_profile_id uuid NOT NULL REFERENCES officer_profiles(id),case_id uuid REFERENCES restoration_cases(id),action_type varchar NOT NULL,preview_payload jsonb NOT NULL,status varchar NOT NULL,version integer NOT NULL DEFAULT 1,expires_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX idx_signal_status ON priority_signals(status,district_id);CREATE INDEX idx_case_status ON restoration_cases(status,district_officer_id);CREATE INDEX idx_mission_assignee ON field_missions(assigned_officer_id,status,due_date);CREATE INDEX idx_evidence_case ON evidence_items(case_id,status);CREATE INDEX idx_audit_case ON audit_events(case_id,created_at);
`)}
  async down(q:QueryRunner){await q.query(`DROP TABLE IF EXISTS ai_action_proposals,audit_events,notifications,monitoring_events,field_observations,milestones,plan_versions,technical_modules,technical_assessments,evidence_gaps,evidence_items,field_missions,case_assignments,restoration_cases,land_patches,signal_decisions,priority_signals,refresh_tokens,officer_profiles,regions,users CASCADE`)}
}
